[package]
name = "codecompanion-tiktoken"
version = "0.1.0"
edition = "2024"

[lib]
name = "tiktoken"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.11.6", features = ["luajit", "module"] }
tiktoken-rs = "0.9.1"
once_cell = "1"
